const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=process.argv[2]||path.join(__dirname,'..');
const elements=new Map(),classes=new Set();
const element=id=>{if(!elements.has(id))elements.set(id,{textContent:'',value:'',innerHTML:'',disabled:false,setAttribute(k,v){this[k]=v},reportValidity(){return true}});return elements.get(id)};
const storage={};
Object.defineProperties(storage,{getItem:{value:k=>storage[k]??null},setItem:{value:(k,v)=>{storage[k]=String(v)}},removeItem:{value:k=>{delete storage[k]}}});
const body={classList:{contains:k=>classes.has(k),add:k=>classes.add(k),remove:k=>classes.delete(k),toggle(k,on){if(on??!classes.has(k)){classes.add(k);return true}classes.delete(k);return false}}};
const ctx=vm.createContext({console,Date,Intl,Math,Number,JSON,setTimeout,window:{},document:{getElementById:element,body,querySelectorAll:()=>[]},localStorage:storage});
const run=s=>vm.runInContext(s,ctx);
const bootstrap=fs.readFileSync(path.join(root,'journal-bootstrap.js'),'utf8');
storage.journal_hide_pnl='true';run(bootstrap);assert(classes.has('is-private'));
const privacyCss=fs.readFileSync(path.join(root,'journal.css'),'utf8');
assert.match(privacyCss,/body\.is-private #netPnl\s*\{/);
assert.doesNotMatch(privacyCss,/body\.is-private\s+:is\(/);
run(fs.readFileSync(path.join(root,'journal.js'),'utf8').split('document.addEventListener("DOMContentLoaded", async () => {')[0]);
(async()=>{
 run('applyPrivacy(true)');assert.equal(element('privacyToggle')['aria-pressed'],'true');
 run('togglePrivacy()');assert.equal(storage.journal_hide_pnl,'false');assert(!classes.has('is-private'));
 run('togglePrivacy()');assert.equal(storage.journal_hide_pnl,'true');assert(classes.has('is-private'));
 run("_session={user:{id:'alice',user_metadata:{}}}");
 await run("saveCreds('secret-report-token','123')");assert.equal(run('getStoredCreds().token'),'secret-report-token');
 assert(!Object.values(storage).includes('secret-report-token'));
 run("_session={user:{id:'bob',user_metadata:{}}}");assert.equal(run('getStoredCreds().token'),'');
 storage['journal_ibkr_token:alice']='old-secret';storage.journal_ibkr_token='legacy';
 run('purgeLegacyCreds()');assert.equal(storage['journal_ibkr_token:alice'],undefined);assert.equal(storage.journal_ibkr_token,undefined);
 assert.doesNotMatch(run(`formatSymbol({symbol:'<img src=x onerror=alert(1)>',asset_class:'STK'})`),/<img/);
 assert.doesNotMatch(run(`ruleBadges({rule_flags:['"><script>alert(1)</script>']})`),/<script/);
 run("_supabase={};_journalProfile={enabled:true,goals:{GBP:{monthlyTarget:8000,tradingDays:16}},rules:{'2026-01-01':true}};state.goalSettingsVersion=null;loadGoalSettings()");
 assert.equal(run('state.monthlyTarget'),8000);assert.equal(run("followedRules('2026-01-01')"),true);
 run("_supabase={};api=async(path,options)=>{globalThis.savedProfile=JSON.parse(options.body);return {ok:true}};");
 assert.equal(run("followedRules('2026-01-01')"),true);
 element('goalMonthlyInput').value='9000';element('goalDaysInput').value='18';await run('saveGoalSettings({preventDefault(){}})');
 assert.equal(run('savedProfile.monthlyTarget'),9000);assert.equal(run('_journalProfile.goals.GBP.monthlyTarget'),9000);
 run("state.rulesDate='2026-01-01'");await run('toggleDayRules()');assert.equal(run('_journalProfile.rules["2026-01-01"]'),false);
 console.log('Passed: privacy hides only Net P&L and survives reload, plus tab-only credentials, user isolation, old-token cleanup, escaping, preferences and stars.');
})().catch(e=>{console.error(e);process.exit(1)});
